[package]
name = "two_makes_ten"
version = "0.1.0"
authors = ["DrewQ"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
